language: node_js

env:
  global:
    - TIMEOUT_MULTIPLIER=12

  matrix:
    - SENECA_VER=seneca@3.x.x
    - SENECA_VER=seneca@plugin
    - SENECA_VER=senecajs/seneca

node_js:
  - '14'
  - '13'
  - '12'
  - '10'

before_script:
  - npm uninstall seneca
  - npm install $SENECA_VER

script:
  - npm test
  - npm audit

after_script:
  - npm run coveralls
